#!/usr/bin/env ruby

def symlink(from, to)
  `ln -sf #{from} #{to}`
end

current_dir = File.expand_path(File.dirname(File.dirname(__FILE__)))

Dir.glob("**/").each do |directory|
  # install symlinks
  Dir["#{directory}/*.symlink"].each do |symlink|
    symlink = symlink.split("//").last
    file = symlink.split(".symlink").first
    destination = File.join(Dir.home, ".#{file}")
    symlink File.join(current_dir, directory, symlink), destination
  end
end

# symlink bins
Dir["bin/*"].each do |bin_file|
  symlink File.join(current_dir, bin_file), "$HOME/#{bin_file}"
end
