#!/usr/bin/env ruby

memes = {
  :fuckyeah       => "http://i.imgur.com/goRhC.jpg",
  :accepted       => "http://i.imgur.com/DWSg1.jpg",
  :forever_alone  => "http://i.imgur.com/sbUCY.jpg",
  :fuuu           => "http://i.imgur.com/oF6We.jpg",
  :okay           => "http://i.imgur.com/6uwGl.jpg",
  :wtf            => "http://i.imgur.com/9oHoJ.png",
  :yuno           => "http://i.imgur.com/RsvdQ.jpg",
  :lol            => "http://i.imgur.com/7r6P7.jpg",
  :confused       => "http://i.imgur.com/lm2p5.jpg",
  :approved       => "http://i.imgur.com/ktL4F.png",
  :fap            => "http://i.imgur.com/kgt81.png",
  :lame           => "http://i.imgur.com/YSrWV.png",
  :newspaper      => "http://i.imgur.com/mdyDE.png",
  :clean          => "http://i.imgur.com/ctqgb.png"
}

input = ARGV.first unless ARGV.empty?

if memes.has_key?(:"#{input}")
  `echo '#{memes[input]}' | pbcopy`
  puts "#{input} copied to clip board"
elsif input == :help
  puts "Available options: "
  memes.each_key { |meme| puts "#{meme}" }	
else
  puts "Argument not valid. Use 'help'."
end
